heat_template_version: queens
parameters:

  vn_name: 
    type: string
    default: "vn-red-hub"

  prefix: 
    type: string
    default: '10.10.10.0'

  mask: 
    type: string 
    default: '29'

  default_ipam: 
    type: string 
    default: 'default-domain:default-project:default-network-ipam'
  rt:
    type: string
    default: target:64512:14 

  vn_ipam:
    type: string
    default: "default-domain:admin:test-ipam"

  policy:
    type: string
    default: "default-domain:admin:test-policy"
resources:
        
  left_vn:
    type: OS::ContrailV2::VirtualNetwork
    properties:
      name: { get_param: vn_name}    
      network_ipam_refs: [{ get_param: default_ipam }]      
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_addr_from_start: "true",
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: prefix },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: mask },
                }
         }]
        }]
      route_target_list:
        {
          route_target_list_route_target: [{ get_param: rt }],
        }


      
  
